### PR TITLE
Fix bug currency can be negtive

### PR DESCRIPTION
**Pull request by jess0407**
https://rockabox.tpondemand.com/entity/9470

### CODE REVIEW

**Comment by jaylett** [comment]
There should probably be a unit test for this behaviour?

**Comment by jess0407** [comment]
noted, will add

**Comment by jess0407** [comment]
Test added :)

**Comment by nwhite89** [comment]
Should there be a message to the user specifying that they can't add negative numbers? also this will need a squash

**Comment by jess0407** [comment]
@nwhite89 have squashed. It will show user the message  'Please enter a valid monetary value.' which cover the case of a negative number.

**Comment by nwhite89** [comment]
Oh yeah ok cool thanks @jess0407 will merge

**Pull request merged**
