### PR TITLE
Add custom validators to rg-text-control

### PR DESCRIPTION
**Pull request by jess0407**
https://rockabox.tpondemand.com/entity/11309

### CODE REVIEW

**Comment by nwhite89** [comment]
is there any tests for these?

**Comment by jess0407** [comment]
@nwhite89  test added, some small css fix to be reviewed by @ohskylab as well.

**Comment by nwhite89** [comment]
thanks @jess0407 Angular side alright @ohskylab to sign off think there should be a squash as well :+1:

**Comment by ohskylab** [comment]
@nwhite89 Yes, if the CSS fix is OK it should be squashed. I'll pick up review this morning.

**Comment by gregbenner** [comment]
@jess0407 @ohskylab Squashy?

**Comment by ohskylab** [comment]
I still need to review. It's in my queue.

**Comment by ohskylab** [comment]
CSS fix dropped; pick it up properly when making *-text-control pseudoclasses play properly with Angular.

No angular changes since approval, so I'm merging.

**Pull request merged**
