### PR TITLE
Add `rb-page-title` demo docs

### PR DESCRIPTION
**Pull request by ohskylab**
TP: https://rockabox.tpondemand.com/entity/8849

Taken from style guide, revised to suit new usage.

Static version retained as reference for extending Angular version.

### CODE REVIEW

**Comment by nwhite89** [comment]
you've removed the directive ?

**Comment by ohskylab** [comment]
@nwhite89 [L21](https://github.com/rockabox/rbx_ui_components/pull/54/files#diff-7b68d9263c912fa49e3e5894133b737cR21) (but doesn't live in `<rb-header>` any more)

**Comment by nwhite89** [comment]
ah klkl! :+1:

**Comment by chrisvxd** [comment]
@ohskylab yeah but you've also removed the directive from the demo :P

**Comment by chrisvxd** [comment]
@ohskylab wait okay so you have done but you've left the static demo in there too. Do we want to show both static and angular markup? Makes sense if so

**Pull request merged**
