### PR TITLE
Refactor Scrollspy

### PR DESCRIPTION
**Pull request by ohskylab**
TP: https://rockabox.tpondemand.com/entity/9649

* Refactor Scrollspy to contain content part and spy part
* Fix `rb-scrollspy` styles

### CODE REVIEW

**Comment by ohskylab** [comment]
DNM: need to test this in CM.

**Comment by ohskylab** [comment]
Added a fix for thi failing test:

```
PhantomJS 1.9.8 (Linux 0.0.0) rb-scrollspy rendering anchors and du-scrollspy attribute directive should place a du-scrollspy `offset` attribute when offset is present in scope FAILED

    Expected '10028' to equal '100'.

        at /home/travis/build/rockabox/rbx_ui_components/test/unit/rb-scrollspy/rb-scrollspy.spec.js:198:0 <- webpack:///test/unit/rb-scrollspy/rb-scrollspy.spec.js:151:0

PhantomJS 1.9.8 (Linux 0.0.0): Executed 354 of 461 (1 FAILED) (0 secs / 3.488 secs)
```

Pretty certain this isn't right, though. I can't figure out whether that's because the test doesn't quite make sense or because the fix for the offset isn't right. @darwinlopez, @chrisvxd: can you take a look, please?

**Comment by jonman** [comment]
Figured it out!
```js
offset="{{(offset || 0) + 28}}"
```
You added `+ 28` but as the offset is a string, this will be `10028`.
Probably need to move that logic into the controller.

**Comment by ohskylab** [comment]
@jonman Thanks! Think this is good to review. Worth testing it in CM.

**Comment by jonman** [comment]
Opened a ticket to address the top item hidden category highlight: https://rockabox.tpondemand.com/entity/10457

**Comment by ohskylab** [comment]
@jonman squashed!

**Comment by ohskylab** [comment]
:fireworks:

**Pull request merged**
