### PR TITLE
Apply some flex box magic to radio groups that are horizontal

### PR DESCRIPTION
**Pull request by gregbenner**
Apply some flex box magic to radio groups that are horizontal

### CODE REVIEW

**Comment by gregbenner** [comment]
@ohskylab when you have a sec.. I visually checked over campaign manager and couldn't spot any negatives as per discussion. ¯\_(ツ)_/¯

**Comment by ohskylab** [comment]
I know this is a bolt-on to the intended purpose of this PR, but I think we should turn this PR into a "Tidy up rb-radio-control", because it's all a bit wrong at the mo.

1. Add demos for the two different rb-radio-control with icon types (should really have done this when updating CM).
2. Use `is-row="true"` on these icon demos, so can test for impact outside CM.
3. Fix docs, specifically "Exactly two radio button and label pairs must be displayed when using the row modifier." 
    * Doesn't hold true for icons, so amend to "...when using the row modifier without the icon modifier."
    * Use only two icons on the no-icon row modifier demo, so demo is accurate.

**Comment by gregbenner** [comment]
Ok closing for now until a ticket appears as it needs more attention.

**Comment by ohskylab** [comment]
Added a story for other fixes, so I'm going to reopen this and merge.

**Pull request merged**
