### PR TITLE
Add useful custom validator 'max-digits', specify a number instead of current 'magic number/ of 28 characters.

### PR DESCRIPTION
**Pull request by gregbenner**
Add useful custom validator 'max-digits', specify a number instead of current 'magic number/ of 28 characters.
TP: https://rockabox.tpondemand.com/entity/11773

### CODE REVIEW

**Comment by nwhite89** [comment]
Think theres been an issue with a rebase here @gregbenner

**Comment by gregbenner** [comment]
Ah yeah.. went back in history a bit too far.. will fixup.

**Comment by nwhite89** [comment]
kl thanks

**Comment by jess0407** [comment]
LGTM

**Pull request merged**
