### PR TITLE
Bump version to 1.1.0

### PR DESCRIPTION
**Pull request by ohskylab**
This is a minor release: see `CHANGELOG.md`.

As this is the first time we've used this approach, I'd like everyone working on or with ui_components
(@darwinlopez, @chrisvxd, @nwhite89, @k0nG, @jonman) to :+1: this before merge. Thanks!

Also, if anyone wants to suggest a naming strategy, I'm all ears.

### CODE REVIEW

**Comment by ohskylab** [comment]
Draft release: https://github.com/rockabox/rbx_ui_components/releases/tag/untagged-366f12f46bfb885f03c9

**Comment by k0nG** [comment]
:+1:

**Comment by ohskylab** [comment]
You may be right, but don't want to take naming candy away from @nwhite89.

**Comment by chrisvxd** [comment]
:+1: from me

**Comment by nwhite89** [comment]
Purple Tiger :+1:

**Comment by ohskylab** [comment]
@darwinlopez gave me a verbal :+1:, as it were, so just @jonman to go.

**Comment by ohskylab** [comment]
(Orange Wallaby)

**Comment by jonman** [comment]
All good :+1:

**Pull request merged**
