### PR TITLE
Fix min-height and not set a static height on the container so footer gets pushed correctly.

### PR DESCRIPTION
**Pull request by gregbenner**
Fix min-height and not set a static height on the container so footer gets pushed correctly.
TP: https://rockabox.tpondemand.com/entity/11696
Reference: https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/

### CODE REVIEW

**Comment by nwhite89** [comment]
This will need to checking within Rig Create @darwinlopez can you please take a look at this thanks

**Comment by gregbenner** [comment]
@darwinlopez Ready to test sticky footer, cheers

**Comment by darwinlopez** [comment]
@gregbenner I'm still getting the previous behaviour on rig_create

**Comment by gregbenner** [comment]
Not possible :S can you double check the UI components is updated when testing? Maybe bower didn't pull correctly.

**Comment by gregbenner** [comment]
Posted on the TP ticket... Create isn't using the rg-site correctly I think.

**Comment by jonman** [comment]
@darwinlopez You ok for me to merge this? Create styling fix should be handled in a separate PR

**Comment by gregbenner** [comment]
La la la, I'm a PR

**Pull request merged**
