### PR TITLE
Refactor targeting scroll spy layout

### PR DESCRIPTION
**Pull request by gregbenner**
Refactor targeting scroll spy layout.

TP: https://rockabox.tpondemand.com/entity/11073

### CODE REVIEW

**Comment by jaylett** [comment]
This isn't a strict refactor; you've also moved to `::` in various places, and it looks like the padding has changed rather than just moved around, although it's difficult to be sure. A more fullsome commit message would help see what's going on here, and make it easier for someone to review it :)

**Comment by gregbenner** [comment]
Yes for sure... the refactor (padding and such) is visual as per the attached TP ticket:
"The scroll spy isn't aligned or spaced properly.
 When the green is showing it is again mis-aligned.
 See screenshot and original design."

The one time binding syntax :: is a best practise in angular for data that doesn't need two way binding. I can add that to the commit message, but felt it was common knowledge with angular developers.

**Comment by gregbenner** [comment]
@jaylett please advise if you would still like more information on the commit message.

**Comment by gregbenner** [comment]
@rockabox/frontend oh heyyy

**Comment by nwhite89** [comment]
As discussed looks likes the padding of the content within the demo has been affected

**Comment by jim-dj** [comment]
Ready for merge to develop for QA

**Pull request merged**
