### PR TITLE
Add `component-display` component

### PR DESCRIPTION
**Pull request by ohskylab**
TP: https://rockabox.tpondemand.com/entity/10405

META COMPONENT.

Review by commit for great sanity.

The original `.ComponentView` styles weren't used in CM, so no fix needed there.

### CODE REVIEW

**Comment by jess0407** [comment]
Hey, there were two merges happened earlier, leaving the following file  to be updated.
- src/rb-generic-form/demo/demo.tpl.html
- src/rb-raw-html-display/demo/demo.tpl.html

**Comment by jess0407** [comment]
Hey, there were two merges happened earlier, leaving the following files to be updated.

src/rb-generic-form/demo/demo.tpl.html
src/rb-raw-html-display/demo/demo.tpl.html

**Comment by ohskylab** [comment]
@jess0407 I've added a fixup for this.

**Comment by jess0407** [comment]
Hey Paul, it looks good to me :)

**Pull request merged**
