### PR TITLE
Refactor `rb-definition-list` to use background images

### PR DESCRIPTION
**Pull request by ohskylab**
TP: https://rockabox.tpondemand.com/entity/10924

I think this just got lost in a story branch, so I'm opening this to get it into `master`.

merge with https://github.com/rockabox/rbx_campaign_management/pull/262

### CODE REVIEW

**Comment by nwhite89** [comment]
Before this is merged there needs to be a test added as tests have been removed instead of replaced

**Comment by ohskylab** [comment]
@nwhite89 good point, added tasks list to reflect.

**Comment by nwhite89** [comment]
@ohskylab cheers :+1: :)

**Comment by gregbenner** [comment]
Can you squash the last 3 commits?

**Comment by ohskylab** [comment]
Probably just want to squash the 4th and 6th together (so it's an update of test, rather than removal and replacement), no?

**Comment by ohskylab** [comment]
@gregbenner @jess0407 we should get this merged ASAP because the matched CM PR has already been merged.

**Comment by gregbenner** [comment]
Think squashin 3 would be fine.. shows new angular work and an adjusted test in one commit?

**Comment by jess0407** [comment]
@gregbenner @ohskylab tried to squash commit 4 and 6 together, git won't let me got stuck.

**Comment by gregbenner** [comment]
I think `git reset --soft HEAD~3; git commit -m "message"; git push --force`

**Comment by jess0407** [comment]
Don't think it worked @gregbenner, my local branch in totally screwed up now, @ohskylab care to squash it on your machine?

**Comment by ohskylab** [comment]
@gregbenner Squashed and green. Look OK to you?

**Comment by gregbenner** [comment]
:camel: Thanks

**Pull request merged**
